# Kuragayala Kenny Joel Pandas

Now we are trying to play with the pandas

## Loading data into Pandas

In [1]:
#porting the pandas library
import pandas as pd   #importing req libraries

In [2]:
#reading the dataset
df = pd.read_csv('F:/SEM 6/ML LAB/ML LAB 1/archive/Best Movies Netflix.csv')

In [3]:
#printing 1st 5 rows of the dataset
print(df.head(5))

   index                                     TITLE  RELEASE_YEAR  SCORE  \
0      0  David Attenborough: A Life on Our Planet          2020    9.0
1      1                                 Inception          2010    8.8
2      2                              Forrest Gump          1994    8.8
3      3                                Anbe Sivam          2003    8.7
4      4                        Bo Burnham: Inside          2021    8.7

   NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
0            31180        83  documentary              GB
1          2268288       148        scifi              GB
2          1994599       142        drama              US
3            20595       160       comedy              IN
4            44074        87       comedy              US

In [4]:
#will be characterstics of dataset
df.describe()

            index  RELEASE_YEAR       SCORE  NUMBER_OF_VOTES    DURATION
count  387.000000    387.000000  387.000000     3.870000e+02  387.000000
mean   193.000000   2011.023256    7.509044     1.365206e+05  123.395349
std    111.861522     10.813874    0.441906     2.342114e+05   28.371632
min      0.000000   1954.000000    6.900000     1.013900e+04   28.000000
25%     96.500000   2008.000000    7.100000     2.051250e+04  103.500000
50%    193.000000   2014.000000    7.400000     4.520000e+04  122.000000
75%    289.500000   2018.000000    7.800000     1.534855e+05  139.000000
max    386.000000   2022.000000    9.000000     2.268288e+06  229.000000

## Reading Data in Pandas

In [5]:
# reading the columns
df.columns

Index(['index', 'TITLE', 'RELEASE_YEAR', 'SCORE', 'NUMBER_OF_VOTES',
       'DURATION', 'MAIN_GENRE', 'MAIN_PRODUCTION'],
      dtype='object')

In [6]:
## Read specific columns
print(df[['TITLE', 'SCORE', 'MAIN_GENRE']]) #look at specific things

                                        TITLE  SCORE   MAIN_GENRE
0    David Attenborough: A Life on Our Planet    9.0  documentary
1                                   Inception    8.8        scifi
2                                Forrest Gump    8.8        drama
3                                  Anbe Sivam    8.7       comedy
4                          Bo Burnham: Inside    8.7       comedy
..                                        ...    ...          ...
382                                  The Trip    6.9       comedy
383                                  The Dirt    6.9        drama
384                                   Top Gun    6.9        drama
385                               Radhe Shyam    6.9      romance
386                       Sorry to Bother You    6.9      fantasy

[387 rows x 3 columns]

In [7]:
## Read Each Row
print(df.iloc[0:4])  #iloc is individual location
for index, row in df.iterrows():
     print(index, row['TITLE'])
df.loc[df['MAIN_GENRE'] == "scifi"] # loc to find specific row mathing the condition

   index                                     TITLE  RELEASE_YEAR  SCORE  \
0      0  David Attenborough: A Life on Our Planet          2020    9.0
1      1                                 Inception          2010    8.8
2      2                              Forrest Gump          1994    8.8
3      3                                Anbe Sivam          2003    8.7

   NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
0            31180        83  documentary              GB
1          2268288       148        scifi              GB
2          1994599       142        drama              US
3            20595       160       comedy              IN
0 David Attenborough: A Life on Our Planet
1 Inception
2 Forrest Gump
3 Anbe Sivam
4 Bo Burnham: Inside
5 Saving Private Ryan
6 Django Unchained
7 Dangal
8 Bo Burnham: Make Happy
9 Louis C.K.: Hilarious
10 Dave Chappelle: Sticks & Stones
11 3 Idiots
12 Black Friday
13 Super Deluxe
14 Winter on Fire: Ukraine's Fight for Freedom
15 Once Upon a Time in America
16 Taxi Driver
17 Like Stars on Earth
18 Bo Burnham: What.
19 Full Metal Jacket
20 Warrior
21 Drishyam
22 Queen
23 Paan Singh Tomar
24 Cowspiracy: The Sustainability Secret
25 Virunga
26 PK
27 BƒÅhubali 2: The Conclusion
28 Monty Python and the Holy Grail
29 Article 15
30 Miracle in Cell No. 7
31 13th
32 Andhadhun
33 Bill Burr: Paper Tiger
34 Udaan
35 How to Train Your Dragon
36 Klaus
37 Swades
38 Minnal Murali
39 Rang De Basanti
40 Seaspiracy
41 Rush
42 Hannah Gadsby: Nanette
43 Barfi!
44 Haider
45 Zindagi Na Milegi Dobara
46 A Silent Voice: The Movie
47 OMG: Oh My God!
48 Talvar
49 Into the Wild
50 Lagaan: Once Upon a Time in India
51 My Octopus Teacher
52 Dil Chahta Hai
53 Mersal
54 The Legend of Bhagat Singh
55 Stand by Me
56 The Exorcist
57 Bombay
58 Dasvi
59 G.O.R.A.
60 Blood Diamond
61 Vizontele
62 Ip Man
63 Her
64 The Bourne Ultimatum
65 Casino Royale
66 Special 26
67 Neon Genesis Evangelion: The End of Evangelion
68 BƒÅhubali: The Beginning
69 Ankhon Dekhi
70 Big Fish
71 Silenced
72 Life of Brian
73 The Invisible Guest
74 Dave Chappelle: The Closer
75 Blade Runner 2049
76 The Imitation Game
77 Jab We Met
78 Free to Play
79 Monty Python Live at the Hollywood Bowl
80 Dev.D
81 Marriage Story
82 Icarus
83 I Am Not Your Negro
84 Ricky Gervais: Humanity
85 Secret Superstar
86 Kal Ho Naa Ho
87 Pad Man
88 Shyam Singha Roy
89 How to Train Your Dragon 2
90 The Irishman
91 Gangaajal
92 The Girl with the Dragon Tattoo
93 Lakshya
94 The Social Network
95 Dunkirk
96 Kai Po Che!
97 The Gentlemen
98 Marco Polo: One Hundred Eyes
99 The Hateful Eight
100 Hunt for the Wilderpeople
101 The Last Samurai
102 Gattaca
103 The Butterfly's Dream
104 14 Peaks: Nothing Is Impossible
105 Nightcrawler
106 Udta Punjab
107 My Fair Lady
108 System Crasher
109 The Game Changers
110 Awakenings
111 Badla
112 Madras Cafe
113 Beasts of No Nation
114 Bonnie and Clyde
115 Roma
116 Kapoor & Sons
117 Mucize
118 Wind River
119 Oye Lucky! Lucky Oye!
120 Dirty Harry
121 Jim & Andy: The Great Beyond - Featuring a Very Special, Contractually Obligated Mention of Tony Clifton
122 Berserk: The Golden Age Arc II - The Battle for Doldrey
123 Silver Linings Playbook
124 Sanju
125 Argo
126 Guru
127 Road to Perdition
128 The Trial of the Chicago 7
129 When Harry Met Sally...
130 Rock On!!
131 In the Family
132 Pyaar Ka Punchnama
133 Midnight in Paris
134 Donnie Brasco
135 The Blind Side
136 Sherlock Holmes
137 Stardust
138 Kuch Kuch Hota Hai
139 Parmanu: The Story of Pokhran
140 Doctor
141 What Happened, Miss Simone?
142 Eddie Murphy Raw
143 Delhi Belly
144 The Boy Who Harnessed the Wind
145 Kabhi Haan Kabhi Naa
146 The Two Popes
147 The Social Dilemma
148 Bad Genius
149 The Mitchells vs. the Machines
150 Gifted Hands: The Ben Carson Story
151 Tell Me Who I Am
152 RBG
153 Highway
154 Athlete A
155 Lupin the Third: The Castle of Cagliostro
156 Love Actually
157 Hell or High Water
158 Wake Up Sid
159 Ludo
160 Stree
161 Aamir
162 I Am Sam
163 True Grit
164 The Distinguished Citizen
165 Jodhaa Akbar
166 The Conjuring
167 Dhamaka
168 Bareilly Ki Barfi
169 Les Mis√©rables
170 Berserk: The Golden Age Arc I - The Egg of the King
171 Dil Se..
172 Omar
173 I Lost My Body
174 tick, tick... BOOM!
175 Coming Soon
176 Nocturnal Animals
177 A Monster Calls
178 On Body and Soul
179 Ala Vaikunthapurramuloo
180 The Devil's Advocate
181 Sivaji: The Boss
182 Happy as Lazzaro
183 The Guns of Navarone
184 Who Am I
185 White Christmas
186 Ip Man 2
187 42
188 Menace II Society
189 Hum Aapke Hain Koun..!
190 Blow
191 Begin Again
192 Uncut Gems
193 Sherlock Holmes: A Game of Shadows
194 Rurouni Kenshin Part I: Origins
195 Forgotten
196 Tamasha
197 Mudbound
198 Lady Bird
199 Molly's Game
200 Raman Raghav 2.0
201 Once Upon a Time in Mumbaai
202 Jaane Tu... Ya Jaane Na
203 Peepli Live
204 Even the Rain
205 Darkest Hour
206 The Bucket List
207 American Factory
208 Miss Americana
209 The Hand of God
210 A Nightmare on Elm Street
211 83
212 Meenakshi Sundareshwar
213 Kurup
214 Crazy, Stupid, Love.
215 Schumacher
216 Guzaarish
217 What the Health
218 Mirage
219 Bully
220 Phantom Thread
221 Looper
222 Felon
223 Life in a Metro
224 Kabhi Khushi Kabhie Gham
225 Kaminey
226 Girl, Interrupted
227 Talaash
228 Starship Troopers
229 The Guernsey Literary & Potato Peel Pie Society
230 Okja
231 Ishqiya
232 The Edge of Seventeen
233 Pyaar Ka Punchnama 2
234 The Nightingale
235 Corpse Bride
236 Memoirs of a Geisha
237 El Camino: A Breaking Bad Movie
238 Official Secrets
239 Coach Carter
240 The King
241 Identity
242 The Best of Enemies
243 The Professionals
244 Raat Akeli Hai
245 Little Women
246 Badhaai Do
247 The Conjuring 2
248 The Fundamentals of Caring
249 The Ballad of Buster Scruggs
250 Shot Caller
251 The Disaster Artist
252 Blue Jay
253 Te3n
254 Monster
255 No One Killed Jessica
256 Toilet: A Love Story
257 Wish Dragon
258 Mom
259 The Professor and the Madman
260 Kabir Singh
261 Dolemite Is My Name
262 In the Line of Fire
263 The Witcher: Nightmare of the Wolf
264 Ittefaq
265 The Tinder Swindler
266 First They Killed My Father
267 Don't Look Up
268 Wazir
269 Gabbar Is Back
270 Fyre
271 Steve Jobs
272 Shooter
273 The Butler
274 The Siege of Jadotville
275 Closer
276 Private Life
277 American Murder: The Family Next Door
278 St. Vincent
279 A River Runs Through It
280 The Patriot
281 Five Feet Apart
282 Michael Clayton
283 The Edge of Democracy
284 Paddington
285 Wedding Association
286 Let Me In
287 Raajneeti
288 Body of Lies
289 The Forgotten Battle
290 Knock Down the House
291 The Call
292 Forgetting Sarah Marshall
293 The Railway Man
294 The Great Hack
295 Paddleton
296 Desperado
297 Gantz:O
298 The Ring
299 Margin Call
300 Copenhagen
301 Black Mirror: Bandersnatch
302 Metallica: Through the Never
303 Seven Years in Tibet
304 Girl
305 Kung Fu Panda 3
306 To All the Boys I've Loved Before
307 Arthur Christmas
308 Trailer Park Boys: The Movie
309 Karthik Calling Karthik
310 The White Tiger
311 Shootout at Lokhandwala
312 The Devil All the Time
313 Tangerine
314 The Danish Girl
315 The Unforgivable
316 Phir Hera Pheri
317 War Dogs
318 The Dig
319 Blade
320 Luck by Chance
321 Namastey London
322 Don
323 Don 2
324 Main Hoon Na
325 Gangubai Kathiawadi
326 Croupier
327 Pieces of a Woman
328 Raw
329 Loving
330 Harold & Kumar Go to White Castle
331 Haseen Dillruba
332 Rose Island
333 Ferry
334 Handsome Devil
335 Torbaaz
336 Ip Man 3
337 The Foreigner
338 Mirai
339 Gaga: Five Foot Two
340 The Christmas Chronicles
341 Sarkar
342 Rambo
343 Dil Dhadakne Do
344 Soul Surfer
345 Happy Gilmore
346 Den of Thieves
347 The Zookeeper's Wife
348 The Platform
349 Public Enemies
350 Ip Man 4: The Finale
351 John Q
352 Fashion
353 Ma Rainey's Black Bottom
354 Any Given Sunday
355 The Long Riders
356 Get on Up
357 Fukrey
358 Chup Chup Ke
359 Then Came You
360 The Wolf's Call
361 Cloudy with a Chance of Meatballs
362 Our Souls at Night
363 Chandigarh Kare Aashiqui
364 Welcome
365 Everybody Knows
366 The Meyerowitz Stories (New and Selected)
367 I Don't Feel at Home in This World Anymore
368 The Highwaymen
369 Legend
370 AK vs AK
371 My Girl
372 Amanda Knox
373 2 States
374 The Power of the Dog
375 The Half of It
376 Outlaw King
377 Mary Kom
378 Suffragette
379 Legend of the Guardians: The Owls of Ga'Hoole
380 Christine
381 The Night Comes for Us
382 The Trip
383 The Dirt
384 Top Gun
385 Radhe Shyam
386 Sorry to Bother You

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
1,1,Inception,2010,8.8,2268288,148,scifi,GB
59,59,G.O.R.A.,2004,8.0,61797,127,scifi,TR
67,67,Neon Genesis Evangelion: The End of Evangelion,1997,8.0,51938,87,scifi,JP
75,75,Blade Runner 2049,2017,8.0,539864,164,scifi,CA
228,228,Starship Troopers,1997,7.3,288960,129,scifi,US
267,267,Don't Look Up,2021,7.2,498447,138,scifi,US
301,301,Black Mirror: Bandersnatch,2018,7.1,123377,90,scifi,GB

## Sorting/Describing Data

In [8]:
df.sort_values(['SCORE'], ascending=[0]) #first col values in asc and 2nd HP in desc. Other options like asce=true or false try

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
0,0,David Attenborough: A Life on Our Planet,2020,9.0,31180,83,documentary,GB
2,2,Forrest Gump,1994,8.8,1994599,142,drama,US
1,1,Inception,2010,8.8,2268288,148,scifi,GB
3,3,Anbe Sivam,2003,8.7,20595,160,comedy,IN
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US
...,...,...,...,...,...,...,...,...
363,363,Chandigarh Kare Aashiqui,2021,6.9,12303,117,crime,IN
364,364,Welcome,2007,6.9,21799,160,romance,IN
365,365,Everybody Knows,2018,6.9,34009,132,drama,IT
366,366,The Meyerowitz Stories (New and Selected),2017,6.9,47971,112,drama,US
386,386,Sorry to Bother You,2018,6.9,75653,111,fantasy,US

## Making changes to the data

In [9]:
#printing 1st 5 rows
df.head(5)

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
0,0,David Attenborough: A Life on Our Planet,2020,9.0,31180,83,documentary,GB
1,1,Inception,2010,8.8,2268288,148,scifi,GB
2,2,Forrest Gump,1994,8.8,1994599,142,drama,US
3,3,Anbe Sivam,2003,8.7,20595,160,comedy,IN
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US

In [10]:
#creating new column trash
df['Trash'] = df['RELEASE_YEAR'] + df['SCORE'] #dataframe
df.head(5)

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION,Trash
0,0,David Attenborough: A Life on Our Planet,2020,9.0,31180,83,documentary,GB,2029.0
1,1,Inception,2010,8.8,2268288,148,scifi,GB,2018.8
2,2,Forrest Gump,1994,8.8,1994599,142,drama,US,2002.8
3,3,Anbe Sivam,2003,8.7,20595,160,comedy,IN,2011.7
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US,2029.7

In [11]:
#deteting trash column
df = df.drop(columns=['Trash'])
df.head(5)

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
0,0,David Attenborough: A Life on Our Planet,2020,9.0,31180,83,documentary,GB
1,1,Inception,2010,8.8,2268288,148,scifi,GB
2,2,Forrest Gump,1994,8.8,1994599,142,drama,US
3,3,Anbe Sivam,2003,8.7,20595,160,comedy,IN
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US

## Filtering Data

In [12]:
#importing regular expression function and trying to play the words which has "in"
import re
df.loc[df['TITLE'].str.contains('In[a-z]*', flags=re.I, regex=True)]

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
1,1,Inception,2010,8.8,2268288,148,scifi,GB
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US
5,5,Saving Private Ryan,1998,8.6,1346020,169,drama,US
6,6,Django Unchained,2012,8.4,1472668,165,western,US
14,14,Winter on Fire: Ukraine's Fight for Freedom,2015,8.3,17710,98,documentary,UA
...,...,...,...,...,...,...,...,...
350,350,Ip Man 4: The Finale,2019,7.0,30694,107,drama,CN
353,353,Ma Rainey's Black Bottom,2020,6.9,50275,94,musical,US
367,367,I Don't Feel at Home in This World Anymore,2017,6.9,55549,93,drama,US
376,376,Outlaw King,2018,6.9,69834,121,drama,GB
380,380,Christine,2016,6.9,14977,115,drama,US

In [13]:
#trying to play around which words of titles starts with 'in'
df.loc[df['TITLE'].str.contains('^In[a-z]*', flags=re.I, regex=True)]

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
1,1,Inception,2010,8.8,2268288,148,scifi,GB
49,49,Into the Wild,2007,8.1,611379,140,drama,US
131,131,In the Family,2017,7.7,23297,124,comedy,TR
262,262,In the Line of Fire,1993,7.2,101939,128,drama,US

## Aggregate Statistics (Groupby)

In [14]:
df = pd.read_csv('F:/SEM 6/ML LAB/ML LAB 1/archive/Best Movies Netflix.csv')
df

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION
0,0,David Attenborough: A Life on Our Planet,2020,9.0,31180,83,documentary,GB
1,1,Inception,2010,8.8,2268288,148,scifi,GB
2,2,Forrest Gump,1994,8.8,1994599,142,drama,US
3,3,Anbe Sivam,2003,8.7,20595,160,comedy,IN
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US
...,...,...,...,...,...,...,...,...
382,382,The Trip,2021,6.9,19706,113,comedy,NO
383,383,The Dirt,2019,6.9,47603,108,drama,US
384,384,Top Gun,1986,6.9,329656,110,drama,US
385,385,Radhe Shyam,2022,6.9,21328,138,romance,IN
386,386,Sorry to Bother You,2018,6.9,75653,111,fantasy,US

In [15]:
df['count'] = 1
df

,index,TITLE,RELEASE_YEAR,SCORE,NUMBER_OF_VOTES,DURATION,MAIN_GENRE,MAIN_PRODUCTION,count
0,0,David Attenborough: A Life on Our Planet,2020,9.0,31180,83,documentary,GB,1
1,1,Inception,2010,8.8,2268288,148,scifi,GB,1
2,2,Forrest Gump,1994,8.8,1994599,142,drama,US,1
3,3,Anbe Sivam,2003,8.7,20595,160,comedy,IN,1
4,4,Bo Burnham: Inside,2021,8.7,44074,87,comedy,US,1
...,...,...,...,...,...,...,...,...,...
382,382,The Trip,2021,6.9,19706,113,comedy,NO,1
383,383,The Dirt,2019,6.9,47603,108,drama,US,1
384,384,Top Gun,1986,6.9,329656,110,drama,US,1
385,385,Radhe Shyam,2022,6.9,21328,138,romance,IN,1
386,386,Sorry to Bother You,2018,6.9,75653,111,fantasy,US,1

In [16]:
df.groupby(['TITLE']).count()
df.groupby(['MAIN_GENRE', 'SCORE']).count()['count']  #get coutn based on multiple attributes in dataset

MAIN_GENRE  SCORE
action      7.1      2
            7.8      1
            8.1      1
            8.4      1
animation   6.9      1
                    ..
western     6.9      1
            7.3      2
            7.6      2
            7.8      1
            8.4      1
Name: count, Length: 118, dtype: int64

## Working with large amounts of data

In [17]:
new_df = pd.DataFrame(columns=df.columns)

for df in pd.read_csv('F:/SEM 6/ML LAB/ML LAB 1/archive/Best Movies Netflix.csv', chunksize=5):   #helps in reading large files in chunks format in case of computation crunch, memory loading issues
    print(df)
    
    results = df.groupby(['MAIN_GENRE']).count()
    
print(results)
    
    #new_df = pd.concat([new_df, results])

   index                                     TITLE  RELEASE_YEAR  SCORE  \
0      0  David Attenborough: A Life on Our Planet          2020    9.0
1      1                                 Inception          2010    8.8
2      2                              Forrest Gump          1994    8.8
3      3                                Anbe Sivam          2003    8.7
4      4                        Bo Burnham: Inside          2021    8.7

   NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
0            31180        83  documentary              GB
1          2268288       148        scifi              GB
2          1994599       142        drama              US
3            20595       160       comedy              IN
4            44074        87       comedy              US
   index                   TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
5      5     Saving Private Ryan          1998    8.6          1346020
6      6        Django Unchained          2012    8.4          1472668
7      7                  Dangal          2016    8.4           180247
8      8  Bo Burnham: Make Happy          2016    8.4            14356
9      9   Louis C.K.: Hilarious          2010    8.4            11973

   DURATION MAIN_GENRE MAIN_PRODUCTION
5       169      drama              US
6       165    western              US
7       161     action              IN
8        60     comedy              US
9        84     comedy              US
    index                                        TITLE  RELEASE_YEAR  SCORE  \
10     10              Dave Chappelle: Sticks & Stones          2019    8.4
11     11                                     3 Idiots          2009    8.4
12     12                                 Black Friday          2004    8.4
13     13                                 Super Deluxe          2019    8.4
14     14  Winter on Fire: Ukraine's Fight for Freedom          2015    8.3

    NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
10            25687        65       comedy              US
11           385782       170       comedy              IN
12            20611       143        crime              IN
13            13680       176     thriller              IN
14            17710        98  documentary              UA
    index                        TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
15     15  Once Upon a Time in America          1984    8.3           342335
16     16                  Taxi Driver          1976    8.3           795222
17     17          Like Stars on Earth          2007    8.3           188234
18     18            Bo Burnham: What.          2013    8.3            11488
19     19            Full Metal Jacket          1987    8.3           723306

    DURATION MAIN_GENRE MAIN_PRODUCTION
15       229      drama              US
16       113      crime              US
17       165      drama              IN
18        60     comedy              US
19       116      drama              GB
    index                                  TITLE  RELEASE_YEAR  SCORE  \
20     20                                Warrior          2011    8.2
21     21                               Drishyam          2015    8.2
22     22                                  Queen          2014    8.2
23     23                       Paan Singh Tomar          2012    8.2
24     24  Cowspiracy: The Sustainability Secret          2014    8.2

    NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
20           463276       140        drama              US
21            79075       163     thriller              IN
22            64805       146        drama              IN
23            35888       135        drama              IN
24            24845        90  documentary              US
    index                            TITLE  RELEASE_YEAR  SCORE  \
25     25                          Virunga          2014    8.2
26     26                               PK          2014    8.2
27     27       BƒÅhubali 2: The Conclusion          2017    8.2
28     28  Monty Python and the Holy Grail          1975    8.2
29     29                       Article 15          2019    8.2

    NUMBER_OF_VOTES  DURATION MAIN_GENRE MAIN_PRODUCTION
25            11403        90        war              CD
26           178012       153     comedy              IN
27            91560       168    fantasy              IN
28           530877        91     comedy              GB
29            32336       130      crime              IN
    index                   TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
30     30   Miracle in Cell No. 7          2019    8.2            46939
31     31                    13th          2016    8.2            34914
32     32               Andhadhun          2018    8.2            88359
33     33  Bill Burr: Paper Tiger          2019    8.1            10649
34     34                   Udaan          2010    8.1            44556

    DURATION   MAIN_GENRE MAIN_PRODUCTION
30       132        drama              TR
31       100  documentary              US
32       139     thriller              IN
33        67       comedy              GB
34       138        drama              IN
    index                     TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
35     35  How to Train Your Dragon          2010    8.1           719717
36     36                     Klaus          2019    8.1           141480
37     37                    Swades          2004    8.1            89085
38     38             Minnal Murali          2021    8.1            24681
39     39           Rang De Basanti          2006    8.1           118092

    DURATION MAIN_GENRE MAIN_PRODUCTION
35        98    fantasy              US
36        97     comedy              ES
37       189      drama              IN
38       158     action              IN
39       157     comedy              IN
    index                   TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
40     40              Seaspiracy          2021    8.1            29604
41     41                    Rush          2013    8.1           465254
42     42  Hannah Gadsby: Nanette          2018    8.1            12035
43     43                  Barfi!          2012    8.1            80643
44     44                  Haider          2014    8.1            54001

    DURATION   MAIN_GENRE MAIN_PRODUCTION
40        80  documentary              US
41       123        drama              US
42        69       comedy              AU
43       151        drama              IN
44       150        drama              IN
    index                      TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
45     45   Zindagi Na Milegi Dobara          2011    8.1            75801
46     46  A Silent Voice: The Movie          2016    8.1            75132
47     47            OMG: Oh My God!          2012    8.1            57449
48     48                     Talvar          2015    8.1            34659
49     49              Into the Wild          2007    8.1           611379

    DURATION MAIN_GENRE MAIN_PRODUCTION
45       166     comedy              IN
46       130    romance              JP
47       125    fantasy              IN
48       132   thriller              IN
49       140      drama              US
    index                              TITLE  RELEASE_YEAR  SCORE  \
50     50  Lagaan: Once Upon a Time in India          2001    8.1
51     51                 My Octopus Teacher          2020    8.1
52     52                     Dil Chahta Hai          2001    8.1
53     53                             Mersal          2017    8.1
54     54         The Legend of Bhagat Singh          2002    8.1

    NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
50           111053       224        drama              IN
51            51232        84  documentary              ZA
52            71167       183        drama              IN
53            32573       169     thriller              IN
54            16225       155        drama              IN
    index         TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  DURATION  \
55     55   Stand by Me          1986    8.1           392790        89
56     56  The Exorcist          1973    8.1           391942       133
57     57        Bombay          1995    8.1            12512       141
58     58         Dasvi          2022    8.0            13140       125
59     59      G.O.R.A.          2004    8.0            61797       127

   MAIN_GENRE MAIN_PRODUCTION
55      drama              US
56     horror              US
57    romance              IN
58      drama              IN
59      scifi              TR
    index                 TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
60     60         Blood Diamond          2006      8           536858
61     61             Vizontele          2001      8            36291
62     62                Ip Man          2008      8           221095
63     63                   Her          2013      8           586679
64     64  The Bourne Ultimatum          2007      8           627009

    DURATION MAIN_GENRE MAIN_PRODUCTION
60       143   thriller              US
61       110     comedy              TR
62       108      drama              HK
63       126      drama              US
64       115   thriller              DE
    index                                           TITLE  RELEASE_YEAR  \
65     65                                   Casino Royale          2006
66     66                                      Special 26          2013
67     67  Neon Genesis Evangelion: The End of Evangelion          1997
68     68                         BƒÅhubali: The Beginning          2015
69     69                                    Ankhon Dekhi          2014

    SCORE  NUMBER_OF_VOTES  DURATION MAIN_GENRE MAIN_PRODUCTION
65      8           644336       139   thriller              GB
66      8            55489       144   thriller              IN
67      8            51938        87      scifi              JP
68      8           117333       159      drama              IN
69      8            11330       104      drama              IN
    index                       TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
70     70                    Big Fish          2003      8           435503
71     71                    Silenced          2011      8            15889
72     72               Life of Brian          1979      8           392419
73     73         The Invisible Guest          2017      8           170351
74     74  Dave Chappelle: The Closer          2021      8            24903

    DURATION MAIN_GENRE MAIN_PRODUCTION
70       125      drama              US
71       125      drama              KR
72        94     comedy              GB
73       107   thriller              ES
74        72     comedy              US
    index                                    TITLE  RELEASE_YEAR  SCORE  \
75     75                        Blade Runner 2049          2017    8.0
76     76                       The Imitation Game          2014    8.0
77     77                               Jab We Met          2007    7.9
78     78                             Free to Play          2014    7.9
79     79  Monty Python Live at the Hollywood Bowl          1982    7.9

    NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
75           539864       164        scifi              CA
76           748654       113     thriller              US
77            51945       138       comedy              IN
78            13308        75  documentary              UA
79            15186        77       comedy              GB
    index                    TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
80     80                    Dev.D          2009    7.9            30389
81     81           Marriage Story          2019    7.9           290643
82     82                   Icarus          2017    7.9            48672
83     83      I Am Not Your Negro          2017    7.9            21632
84     84  Ricky Gervais: Humanity          2018    7.9            18523

    DURATION   MAIN_GENRE MAIN_PRODUCTION
80       144        drama              IN
81       136        drama              GB
82       121  documentary              US
83        93  documentary              BE
84        79       comedy              GB
    index                       TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
85     85            Secret Superstar          2017    7.9            24046
86     86               Kal Ho Naa Ho          2003    7.9            68028
87     87                     Pad Man          2018    7.9            25269
88     88            Shyam Singha Roy          2021    7.9            10903
89     89  How to Train Your Dragon 2          2014    7.8           327565

    DURATION MAIN_GENRE MAIN_PRODUCTION
85       150      drama              IN
86       186      drama              IN
87       140     comedy              IN
88       157      drama              IN
89       102    fantasy              US
    index                            TITLE  RELEASE_YEAR  SCORE  \
90     90                     The Irishman          2019    7.8
91     91                        Gangaajal          2003    7.8
92     92  The Girl with the Dragon Tattoo          2011    7.8
93     93                          Lakshya          2004    7.8
94     94               The Social Network          2010    7.8

    NUMBER_OF_VOTES  DURATION MAIN_GENRE MAIN_PRODUCTION
90           371209       209      drama              US
91            17029       157      drama              IN
92           454917       158      crime              NO
93            23076       186      drama              IN
94           681286       121      drama              US
    index                         TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
95     95                       Dunkirk          2017    7.8           619645
96     96                   Kai Po Che!          2013    7.8            36512
97     97                 The Gentlemen          2019    7.8           314049
98     98  Marco Polo: One Hundred Eyes          2015    7.8            10742
99     99             The Hateful Eight          2015    7.8           570138

    DURATION MAIN_GENRE MAIN_PRODUCTION
95       107      drama              US
96       126      drama              IN
97       113     comedy              US
98        28     action              US
99       188    western              US
     index                            TITLE  RELEASE_YEAR  SCORE  \
100    100        Hunt for the Wilderpeople          2016    7.8
101    101                 The Last Samurai          2003    7.8
102    102                          Gattaca          1997    7.8
103    103            The Butterfly's Dream          2013    7.8
104    104  14 Peaks: Nothing Is Impossible          2021    7.8

     NUMBER_OF_VOTES  DURATION   MAIN_GENRE MAIN_PRODUCTION
100           125720       101       comedy              NZ
101           429097       154        drama              NZ
102           298168       106     thriller              US
103            21882       138        drama              TR
104            22858       101  documentary              US
     index              TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  DURATION  \
105    105       Nightcrawler          2014    7.8           523686       118
106    106        Udta Punjab          2016    7.8            29819       148
107    107       My Fair Lady          1964    7.8            94121       170
108    108     System Crasher          2019    7.8            12699       118
109    109  The Game Changers          2019    7.8            19708        88

      MAIN_GENRE MAIN_PRODUCTION
105        crime              US
106        crime              IN
107        drama              US
108        drama              DE
109  documentary              US
     index                TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
110    110           Awakenings          1990    7.8           137549
111    111                Badla          2019    7.8            27130
112    112          Madras Cafe          2013    7.7            24319
113    113  Beasts of No Nation          2015    7.7            80129
114    114     Bonnie and Clyde          1967    7.7           111189

     DURATION MAIN_GENRE MAIN_PRODUCTION
110       120      drama              US
111       120   thriller              IN
112       130   thriller              IN
113       137        war              US
114       110      drama              US
     index                  TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
115    115                   Roma          2018    7.7           153508
116    116          Kapoor & Sons          2016    7.7            25792
117    117                 Mucize          2015    7.7            12395
118    118             Wind River          2017    7.7           240408
119    119  Oye Lucky! Lucky Oye!          2008    7.7            17411

     DURATION MAIN_GENRE MAIN_PRODUCTION
115       135      drama              MX
116       132    romance              IN
117       136      drama              TR
118       106   thriller              FR
119       126     comedy              IN
     index                                              TITLE  RELEASE_YEAR  \
120    120                                        Dirty Harry          1971
121    121  Jim & Andy: The Great Beyond - Featuring a Ver...          2017
122    122  Berserk: The Golden Age Arc II - The Battle fo...          2012
123    123                            Silver Linings Playbook          2012
124    124                                              Sanju          2018

     SCORE  NUMBER_OF_VOTES  DURATION MAIN_GENRE MAIN_PRODUCTION
120    7.7           153463       102   thriller              US
121    7.7            25593        94     comedy              US
122    7.7            10257        80    fantasy              JP
123    7.7           697481       122      drama              US
124    7.7            52227       161      drama              IN
     index                       TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
125    125                        Argo          2012    7.7           600392
126    126                        Guru          2007    7.7            23541
127    127           Road to Perdition          2002    7.7           263212
128    128  The Trial of the Chicago 7          2020    7.7           170728
129    129     When Harry Met Sally...          1989    7.7           212913

     DURATION MAIN_GENRE MAIN_PRODUCTION
125       120      drama              US
126       166    romance              IN
127       117   thriller              US
128       130      drama              US
129        96    romance              US
     index               TITLE  RELEASE_YEAR  SCORE  NUMBER_OF_VOTES  \
130    130           Rock On!!          2008    7.7            21963
131    131       In the Family          2017    7.7            23297
132    132  Pyaar Ka Punchnama          2011    7.7            21204
133    133   Midnight in Paris          2011    7.7           413541
134    134       Donnie Brasco          1997    7.7           300073

     DURATION MAIN_GENRE MAIN_PRODUCTION
130       144      drama              IN
131       124     comedy              TR
132       149    romance              IN
133        94    fantasy              US
134       127   thriller              US
     index                          TITLE  RELEASE_YEAR  SCORE  \
135    135                 The Blind Side          2009    7.6
136    136                Sherlock Holmes          2009    7.6
137    137                       Stardust          2007    7.6
138    138             Kuch Kuch Hota Hai          1998    7.6
139    139  Parmanu: The Story of Pokhran          2018    7.6

     NUMBER_OF_VOTES  DURATION MAIN_GENRE MAIN_PRODUCTION
135           323939       129      drama              US
136           620154       129      crime              GB